export const GET_SINGLEPRODUCT_REQUEST = 'GET_SINGLEPRODUCT_REQUEST'
export const GET_SINGLEPRODUCT_SUCCESS = 'GET_SINGLEPRODUCT_SUCCESS'
export const GET_SINGLEPRODUCT_FAILURE = 'GET_SINGLEPRODUCT_FAILURE'