export const Add_Product_Request = 'Add_Product_Request'
export const Add_Product_Success = 'Add_Product_Success'
export const Add_Product_Failure = 'Add_Product_Failure'
export const Edit_Product_Success = 'Edit_Product_Success'
export const Get_User_Success = 'Get_User_Success'